### ISSUE TITLE
`assignment2` 필수&선택과제

### ISSUE THREAD

**Issue by seunguri** [LikeLion-at-CAU-10th/Mingyu-Kim#3]
## 필수 과제 
![image](https://user-images.githubusercontent.com/52988414/161801067-a57e27cf-4d45-41b5-99b6-4eacf9991018.png)
왕 봄이다
정갈한 게시판 사이트는 space-evenly가 딱이죠

## 선택 과제
![image](https://user-images.githubusercontent.com/52988414/161802427-520eb883-defe-46fc-9b84-37783019d6ed.png)
김민규 최고
flex-basis 소수점 까지 있는 거 보고 박수쳤어요.
flex-direction, justify-content 다양하게 쓴 것도 정말 수고했어요

코드가 왕 긴데 팁을 드리자면
공통된 요소들을 한 class 에 묶고 특징이 다른 class를 만들어서 둘 다 사용하면 좋아요.
html class 는 저렇게 띄어쓰기로 두개 넣고!
```html
            <div class = "box box1">box1</div>
            <div class = "box box2">box2</div>
```
css는 이렇게!
```css
.box{
    display : flex;
    justify-content: center;
    align-items: center;
}

.box1 {
    flex-basis : 19.8%;
    background-color: salmon;
}

.box2{
    flex-basis : 76.8%;
    background-color: orange;
}

```
